print("Hello World!")
print("2+3")
print(2+3)
print("Your new score is", 1030+10)
print("Your new score is", "1030+10")
print("Your new score is,", 1030+10)
print("Your new score is,", 1030+10)
print("Based on the calculations of this student\r his answer is incorrect")
print("Based on the calculations of this student\n his answer is incorrect")